
version: "3.3"

services:
  jupyter:
    build:
      context: .
    ports:
      - "8888:8888"
    # dockertoolbox only mount c:/Users
    # so many hours wasted Jesus.
    # https://github.com/docker/kitematic/issues/2738
    volumes:
        - C:\Users\baram204\dev\lgo\mlgo_execercise:/mlgo_execercise

# comment original. cause that's now working on windonws 10 environment.

#    source:
#    - type: "bind"
#      source: ./../../examples
#      target: /examples
